### ISSUE TITLE
Bossbar text doesn't change, bossbar itself does

### ISSUE THREAD

**Issue by WoutDev** [confuser/BarAPI#41]
Issue: I have a timer that decreases the bossbar each time with x% and change the text of the bossbar. I tested it with three accounts online at the same moment: 1.7.9, 1.7.10 and 1.8. On the 1.7.9 and 1.7.10 there is no problem, everything updates smoothly but on 1.8 the text doesn't update (but the health updates)

No errors at the console.

Animated gif:
How it needs to be: http://gyazo.com/dfb3684dd504d400fa65e84588fdf7d1
How it is: http://gyazo.com/fe5ae151ef589e8057f387ef42b20848

The two gifs are two different accounts online at the same time. One account is 1.7.9 (works perfectly) and the other account is 1.8. (Doesn't update the text).

Can I do something about to fix this, or is this BarAPI itself (or the just something client-side)?

I'm using the latest build of BarAPI downloaded from:
http://ci.frostcast.net/job/BarAPI/lastBuild/

useSpigotHack is true on the config.

**Comment by games647** [comment]
Same for me. I have to remove the bar first in order to change the text.
