### ISSUE TITLE
Any way to block default Wither Boss Bar?

### ISSUE THREAD

**Issue by Cryptite** [confuser/BarAPI#49]
I have a situation where I have a custom wither mob and I'd like to show his Bar only to players within 15 blocks of him. Is there any way to block the default Wither bar showing up (basically to all of the players in the small map we're dealing with) so I can use BarAPI instead? Or perhaps modify the wither bar to reduce the distance it's shown to nearby players?

Currently I'm using BarAPI to show his health but then the vanilla bar still pops up and they fight each other presently.

**Comment by confuser** [comment]
There's no way to prevent the vanilla bar from showing I'm afraid. This is all handled client side, so there's very little that can be done.

One possible solution however is to use BarAPI only for players that are too far away from your custom wither mob to see the vanilla bar.

**Comment by Cryptite** [comment]
The biggest issue is the need to keep the bar showing only for close-by players. I'm building a MOBA style pvp map and attacking the wither should be something that could be pulled off quietly; but since the entire map sees the bar the minute the thing is attacked, it kind of ruins that whole idea.

May have to come up with some other solution.
