### ISSUE TITLE
BarAPI Update for 1.8

### ISSUE THREAD

**Issue by zrocweb** [confuser/BarAPI#52]
get these errors when joining as well as when it tries to broadcast.  currently running Spigot 1.8.x

25.02 10:29:15 [Multicraft] zrocweb ran command Message of the Day
25.02 10:29:15 [Connect] User zrocweb, IP xxx.xxx.xxx.xxx
25.02 10:29:15 [Multicraft] Skipped 132 lines due to rate limit (30/s)
25.02 10:29:13 [Server] WARN at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
25.02 10:29:13 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785)
25.02 10:29:13 [Server] WARN at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82)
25.02 10:29:13 [Server] WARN at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159)
25.02 10:29:13 [Server] WARN at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41)
25.02 10:29:13 [Server] WARN at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109)
25.02 10:29:13 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:148)
25.02 10:29:13 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:263)
25.02 10:29:13 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
25.02 10:29:13 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
25.02 10:29:13 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
25.02 10:29:13 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
25.02 10:29:13 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:606)
25.02 10:29:13 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25.02 10:29:13 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
25.02 10:29:13 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
25.02 10:29:13 [Server] WARN at me.henryjake121.BossBar.PlayerListener.onPlayerJoin(PlayerListener.java:22)
25.02 10:29:13 [Server] WARN at me.confuser.barapi.BarAPI.setMessage(BarAPI.java:200)
25.02 10:29:13 [Server] WARN at me.confuser.barapi.BarAPI.getDragon(BarAPI.java:446)
25.02 10:29:13 [Server] WARN at me.confuser.barapi.BarAPI.addDragon(BarAPI.java:452)
25.02 10:29:13 [Server] WARN at me.confuser.barapi.nms.v1_8Fake.getSpawnPacket(v1_8Fake.java:30)
25.02 10:29:13 [Server] WARN at me.confuser.barapi.Util.getCraftClass(Util.java:106)
25.02 10:29:13 [Server] WARN at java.lang.Class.forName(Class.java:191)
25.02 10:29:13 [Server] WARN at java.lang.Class.forName0(Native Method)
25.02 10:29:13 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
25.02 10:29:13 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
25.02 10:29:13 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
25.02 10:29:13 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
25.02 10:29:13 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.Entity

**Comment by lishaodong** [comment]
I have same problem. The package net.minecraft.server.v1_7_R4 can't be found because spigot 1.8 use v1_8_R2. I found you set it as v1_7_R4 in Util.java, please change this part.

And you guys also need to change nms code accordingly, in v1_8_R2, the constructor of ````PacketPlayOutEntityTeleport```` also changed.

Thanks for your work.

**Comment by confuser** [comment]
Incorrect, v1_7_R4 is only used for the protocol hack.

I'll take a look at the changes to PacketPlayOutEntityTeleport in 1.8.3 and push an update.
