### ISSUE TITLE
Maven repository broken

### ISSUE THREAD

**Issue by MattBDev** [confuser/BarAPI#60]
Title explains itself

**Comment by confuser** [comment]
Which versions are you missing?

**Comment by cbarber** [comment]
Any and all. Have a look at: http://ci.frostcast.net/plugin/repository/everything/me/confuser/BarAPI/3.4-SNAPSHOT/. There are no jars.

**Comment by confuser** [comment]
Apologies. I'll fix this shortly.

**Comment by games647** [comment]
And?

**Comment by confuser** [comment]
`3.4-SNAPSHOT`
