### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by JugadorON** [confuser/BarAPI#64]
https://dev.bukkit.org/bukkit-plugins/bar-api/

I need version to 1.10.2, please!!!

Java 8!

**Comment by confuser** [comment]
BarAPI was deprecated last release. Plugin developers should have migrated to the new Bukkit API implemented in Spigot by now. Which plugin is this affecting?

**Comment by confuser** [comment]
I've released v3.5 which will support 1.9+ going forwards
